-- CC Switch SQLite 导出
-- Fixture authority: cc-switch-cli commit 3c3a7f9d602dab2932f02e764a628ccca5285b0d
-- Generated by that revision's own Database initialization and config export path.
-- 生成时间: 2026-08-01 16:25:13
-- user_version: 13
PRAGMA foreign_keys=OFF;
PRAGMA user_version=13;
BEGIN TRANSACTION;
CREATE TABLE mcp_servers (
            id TEXT PRIMARY KEY, name TEXT NOT NULL, server_config TEXT NOT NULL,
            description TEXT, homepage TEXT, docs TEXT, tags TEXT NOT NULL DEFAULT '[]',
            enabled_claude BOOLEAN NOT NULL DEFAULT 0, enabled_codex BOOLEAN NOT NULL DEFAULT 0,
            enabled_gemini BOOLEAN NOT NULL DEFAULT 0, enabled_opencode BOOLEAN NOT NULL DEFAULT 0,
            enabled_hermes BOOLEAN NOT NULL DEFAULT 0
        );
CREATE TABLE model_pricing (
            model_id TEXT PRIMARY KEY, display_name TEXT NOT NULL,
            input_cost_per_million TEXT NOT NULL, output_cost_per_million TEXT NOT NULL,
            cache_read_cost_per_million TEXT NOT NULL DEFAULT '0',
            cache_creation_cost_per_million TEXT NOT NULL DEFAULT '0'
        );
CREATE TABLE profiles (
                id TEXT PRIMARY KEY,
                name TEXT NOT NULL,
                payload TEXT NOT NULL,
                sort_order INTEGER,
                created_at INTEGER,
                updated_at INTEGER
            );
CREATE TABLE prompts (
            id TEXT NOT NULL, app_type TEXT NOT NULL, name TEXT NOT NULL, content TEXT NOT NULL,
            description TEXT, enabled BOOLEAN NOT NULL DEFAULT 1, created_at INTEGER, updated_at INTEGER,
            PRIMARY KEY (id, app_type)
        );
CREATE TABLE provider_endpoints (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                provider_id TEXT NOT NULL,
                app_type TEXT NOT NULL,
                url TEXT NOT NULL,
                added_at INTEGER,
                FOREIGN KEY (provider_id, app_type) REFERENCES providers(id, app_type) ON DELETE CASCADE
            );
CREATE TABLE provider_health (
            provider_id TEXT NOT NULL, app_type TEXT NOT NULL, is_healthy INTEGER NOT NULL DEFAULT 1,
            consecutive_failures INTEGER NOT NULL DEFAULT 0, last_success_at TEXT, last_failure_at TEXT,
            last_error TEXT, updated_at TEXT NOT NULL,
            PRIMARY KEY (provider_id, app_type),
            FOREIGN KEY (provider_id, app_type) REFERENCES providers(id, app_type) ON DELETE CASCADE
        );
CREATE TABLE providers (
                id TEXT NOT NULL,
                app_type TEXT NOT NULL,
                name TEXT NOT NULL,
                settings_config TEXT NOT NULL,
                website_url TEXT,
                category TEXT,
                created_at INTEGER,
                sort_index INTEGER,
                notes TEXT,
                icon TEXT,
                icon_color TEXT,
                meta TEXT NOT NULL DEFAULT '{}',
                is_current BOOLEAN NOT NULL DEFAULT 0,
                in_failover_queue BOOLEAN NOT NULL DEFAULT 0, "cost_multiplier" TEXT NOT NULL DEFAULT '1.0', "limit_daily_usd" TEXT, "limit_monthly_usd" TEXT, "provider_type" TEXT,
                PRIMARY KEY (id, app_type)
            );
CREATE TABLE proxy_config (
            app_type TEXT PRIMARY KEY CHECK (app_type IN ('claude','codex','gemini')),
            proxy_enabled INTEGER NOT NULL DEFAULT 0, listen_address TEXT NOT NULL DEFAULT '127.0.0.1',
            listen_port INTEGER NOT NULL DEFAULT 15721, enable_logging INTEGER NOT NULL DEFAULT 1,
            enabled INTEGER NOT NULL DEFAULT 0, auto_failover_enabled INTEGER NOT NULL DEFAULT 0,
            max_retries INTEGER NOT NULL DEFAULT 3, streaming_first_byte_timeout INTEGER NOT NULL DEFAULT 60,
            streaming_idle_timeout INTEGER NOT NULL DEFAULT 120, non_streaming_timeout INTEGER NOT NULL DEFAULT 600,
            circuit_failure_threshold INTEGER NOT NULL DEFAULT 4, circuit_success_threshold INTEGER NOT NULL DEFAULT 2,
            circuit_timeout_seconds INTEGER NOT NULL DEFAULT 60, circuit_error_rate_threshold REAL NOT NULL DEFAULT 0.6,
            circuit_min_requests INTEGER NOT NULL DEFAULT 10,
            default_cost_multiplier TEXT NOT NULL DEFAULT '1',
            pricing_model_source TEXT NOT NULL DEFAULT 'response',
            created_at TEXT NOT NULL DEFAULT (datetime('now')), updated_at TEXT NOT NULL DEFAULT (datetime('now'))
        , live_takeover_active INTEGER NOT NULL DEFAULT 0);
CREATE TABLE proxy_failover_live_snapshots (
            app_type TEXT NOT NULL,
            provider_id TEXT NOT NULL,
            config_json TEXT NOT NULL,
            generated_at TEXT NOT NULL,
            PRIMARY KEY (app_type, provider_id),
            FOREIGN KEY (provider_id, app_type) REFERENCES providers(id, app_type) ON DELETE CASCADE
        );
CREATE TABLE proxy_live_backup (
            app_type TEXT PRIMARY KEY, original_config TEXT NOT NULL, backed_up_at TEXT NOT NULL
        );
CREATE TABLE proxy_request_logs (
            request_id TEXT PRIMARY KEY, provider_id TEXT NOT NULL, app_type TEXT NOT NULL, model TEXT NOT NULL,
            request_model TEXT,
            pricing_model TEXT,
            input_tokens INTEGER NOT NULL DEFAULT 0, output_tokens INTEGER NOT NULL DEFAULT 0,
            cache_read_tokens INTEGER NOT NULL DEFAULT 0, cache_creation_tokens INTEGER NOT NULL DEFAULT 0,
            input_token_semantics INTEGER NOT NULL DEFAULT 0,
            input_cost_usd TEXT NOT NULL DEFAULT '0', output_cost_usd TEXT NOT NULL DEFAULT '0',
            cache_read_cost_usd TEXT NOT NULL DEFAULT '0', cache_creation_cost_usd TEXT NOT NULL DEFAULT '0',
            total_cost_usd TEXT NOT NULL DEFAULT '0', latency_ms INTEGER NOT NULL, first_token_ms INTEGER,
            duration_ms INTEGER, status_code INTEGER NOT NULL, error_message TEXT, session_id TEXT,
            provider_type TEXT, is_streaming INTEGER NOT NULL DEFAULT 0,
            cost_multiplier TEXT NOT NULL DEFAULT '1.0', created_at INTEGER NOT NULL,
            data_source TEXT NOT NULL DEFAULT 'proxy'
        );
CREATE TABLE session_log_sync (
                file_path TEXT PRIMARY KEY,
                last_modified INTEGER NOT NULL,
                last_line_offset INTEGER NOT NULL DEFAULT 0,
                last_synced_at INTEGER NOT NULL
            );
CREATE TABLE settings (key TEXT PRIMARY KEY, value TEXT);
CREATE TABLE skill_repos (
            owner TEXT NOT NULL, name TEXT NOT NULL, branch TEXT NOT NULL DEFAULT 'main',
            enabled BOOLEAN NOT NULL DEFAULT 1, PRIMARY KEY (owner, name)
        );
CREATE TABLE skills (
            id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            description TEXT,
            directory TEXT NOT NULL,
            repo_owner TEXT,
            repo_name TEXT,
            repo_branch TEXT DEFAULT 'main',
            readme_url TEXT,
            enabled_claude BOOLEAN NOT NULL DEFAULT 0,
            enabled_codex BOOLEAN NOT NULL DEFAULT 0,
            enabled_gemini BOOLEAN NOT NULL DEFAULT 0,
            enabled_opencode BOOLEAN NOT NULL DEFAULT 0,
            enabled_hermes BOOLEAN NOT NULL DEFAULT 0,
            installed_at INTEGER NOT NULL DEFAULT 0,
            content_hash TEXT,
            updated_at INTEGER NOT NULL DEFAULT 0
        );
CREATE TABLE stream_check_logs (
            id INTEGER PRIMARY KEY AUTOINCREMENT, provider_id TEXT NOT NULL, provider_name TEXT NOT NULL,
            app_type TEXT NOT NULL, status TEXT NOT NULL, success INTEGER NOT NULL, message TEXT NOT NULL,
            response_time_ms INTEGER, http_status INTEGER, model_used TEXT,
            retry_count INTEGER DEFAULT 0, tested_at INTEGER NOT NULL
        );
CREATE TABLE usage_daily_rollups (
                date TEXT NOT NULL,
                app_type TEXT NOT NULL,
                provider_id TEXT NOT NULL,
                model TEXT NOT NULL,
                request_model TEXT NOT NULL DEFAULT '',
                pricing_model TEXT NOT NULL DEFAULT '',
                request_count INTEGER NOT NULL DEFAULT 0,
                success_count INTEGER NOT NULL DEFAULT 0,
                input_tokens INTEGER NOT NULL DEFAULT 0,
                output_tokens INTEGER NOT NULL DEFAULT 0,
                cache_read_tokens INTEGER NOT NULL DEFAULT 0,
                cache_creation_tokens INTEGER NOT NULL DEFAULT 0,
                input_token_semantics INTEGER NOT NULL DEFAULT 0,
                total_cost_usd TEXT NOT NULL DEFAULT '0',
                avg_latency_ms INTEGER NOT NULL DEFAULT 0,
                PRIMARY KEY (date, app_type, provider_id, model, request_model, pricing_model)
            );
CREATE INDEX idx_providers_failover
             ON providers(app_type, in_failover_queue, sort_index);
CREATE INDEX idx_request_logs_app_created_at
                 ON proxy_request_logs(app_type, created_at DESC);
CREATE INDEX idx_request_logs_created_at ON proxy_request_logs(created_at);
CREATE INDEX idx_request_logs_dedup_lookup_expr
                 ON proxy_request_logs(app_type, COALESCE(data_source, 'proxy'), input_tokens,
                                       output_tokens, cache_read_tokens, created_at,
                                       cache_creation_tokens);
CREATE INDEX idx_request_logs_model ON proxy_request_logs(model);
CREATE INDEX idx_request_logs_provider ON proxy_request_logs(provider_id, app_type);
CREATE INDEX idx_request_logs_session ON proxy_request_logs(session_id);
CREATE INDEX idx_request_logs_status ON proxy_request_logs(status_code);
CREATE INDEX idx_stream_check_logs_provider
             ON stream_check_logs(app_type, provider_id, tested_at DESC);
INSERT INTO "mcp_servers" ("id", "name", "server_config", "description", "homepage", "docs", "tags", "enabled_claude", "enabled_codex", "enabled_gemini", "enabled_opencode", "enabled_hermes") VALUES ('v13-mcp', 'V13 MCP', '{"command":"fixture","args":[]}', NULL, NULL, NULL, '[]', 1, 0, 0, 0, 1);
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('claude-opus-4-8', 'Claude Opus 4.8', '5', '25', '0.50', '6.25');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('claude-opus-4-7', 'Claude Opus 4.7', '5', '25', '0.50', '6.25');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('claude-opus-4-6-20260206', 'Claude Opus 4.6', '5', '25', '0.50', '6.25');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('claude-sonnet-4-6-20260217', 'Claude Sonnet 4.6', '3', '15', '0.30', '3.75');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('claude-opus-4-5-20251101', 'Claude Opus 4.5', '5', '25', '0.50', '6.25');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('claude-sonnet-4-5-20250929', 'Claude Sonnet 4.5', '3', '15', '0.30', '3.75');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('claude-haiku-4-5-20251001', 'Claude Haiku 4.5', '1', '5', '0.10', '1.25');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('claude-opus-4-20250514', 'Claude Opus 4', '15', '75', '1.50', '18.75');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('claude-opus-4-1-20250805', 'Claude Opus 4.1', '15', '75', '1.50', '18.75');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('claude-sonnet-4-20250514', 'Claude Sonnet 4', '3', '15', '0.30', '3.75');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('claude-3-5-haiku-20241022', 'V13 User Price', '13.13', '4', '0.08', '1');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet', '3', '15', '0.30', '3.75');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5.5', 'GPT-5.5', '5', '30', '0.50', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5.5-low', 'GPT-5.5', '5', '30', '0.50', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5.5-medium', 'GPT-5.5', '5', '30', '0.50', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5.5-high', 'GPT-5.5', '5', '30', '0.50', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5.5-xhigh', 'GPT-5.5', '5', '30', '0.50', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5.5-minimal', 'GPT-5.5', '5', '30', '0.50', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5.4', 'GPT-5.4', '2.50', '15', '0.25', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5.4-mini', 'GPT-5.4 Mini', '0.75', '4.50', '0.075', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5.4-nano', 'GPT-5.4 Nano', '0.20', '1.25', '0.02', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5.2', 'GPT-5.2', '1.75', '14', '0.175', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5.2-low', 'GPT-5.2', '1.75', '14', '0.175', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5.2-medium', 'GPT-5.2', '1.75', '14', '0.175', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5.2-high', 'GPT-5.2', '1.75', '14', '0.175', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5.2-xhigh', 'GPT-5.2', '1.75', '14', '0.175', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5.2-codex', 'GPT-5.2 Codex', '1.75', '14', '0.175', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5.2-codex-low', 'GPT-5.2 Codex', '1.75', '14', '0.175', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5.2-codex-medium', 'GPT-5.2 Codex', '1.75', '14', '0.175', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5.2-codex-high', 'GPT-5.2 Codex', '1.75', '14', '0.175', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5.2-codex-xhigh', 'GPT-5.2 Codex', '1.75', '14', '0.175', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5.3-codex', 'GPT-5.3 Codex', '1.75', '14', '0.175', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5.3-codex-low', 'GPT-5.3 Codex', '1.75', '14', '0.175', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5.3-codex-medium', 'GPT-5.3 Codex', '1.75', '14', '0.175', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5.3-codex-high', 'GPT-5.3 Codex', '1.75', '14', '0.175', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5.3-codex-xhigh', 'GPT-5.3 Codex', '1.75', '14', '0.175', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5.1', 'GPT-5.1', '1.25', '10', '0.125', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5.1-low', 'GPT-5.1', '1.25', '10', '0.125', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5.1-medium', 'GPT-5.1', '1.25', '10', '0.125', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5.1-high', 'GPT-5.1', '1.25', '10', '0.125', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5.1-minimal', 'GPT-5.1', '1.25', '10', '0.125', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5.1-codex', 'GPT-5.1 Codex', '1.25', '10', '0.125', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5.1-codex-mini', 'GPT-5.1 Codex', '1.25', '10', '0.125', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5.1-codex-max', 'GPT-5.1 Codex', '1.25', '10', '0.125', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5.1-codex-max-high', 'GPT-5.1 Codex', '1.25', '10', '0.125', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5.1-codex-max-xhigh', 'GPT-5.1 Codex', '1.25', '10', '0.125', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5', 'GPT-5', '1.25', '10', '0.125', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5-low', 'GPT-5', '1.25', '10', '0.125', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5-medium', 'GPT-5', '1.25', '10', '0.125', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5-high', 'GPT-5', '1.25', '10', '0.125', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5-minimal', 'GPT-5', '1.25', '10', '0.125', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5-codex', 'GPT-5 Codex', '1.25', '10', '0.125', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5-codex-low', 'GPT-5 Codex', '1.25', '10', '0.125', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5-codex-medium', 'GPT-5 Codex', '1.25', '10', '0.125', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5-codex-high', 'GPT-5 Codex', '1.25', '10', '0.125', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5-codex-mini', 'GPT-5 Codex', '1.25', '10', '0.125', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5-codex-mini-medium', 'GPT-5 Codex', '1.25', '10', '0.125', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5-codex-mini-high', 'GPT-5 Codex', '1.25', '10', '0.125', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('o3', 'OpenAI o3', '2', '8', '0.50', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('o4-mini', 'OpenAI o4-mini', '1.10', '4.40', '0.275', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-4.1', 'GPT-4.1', '2', '8', '0.50', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-4.1-mini', 'GPT-4.1 Mini', '0.40', '1.60', '0.10', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-4.1-nano', 'GPT-4.1 Nano', '0.10', '0.40', '0.025', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gemini-3.1-pro-preview', 'Gemini 3.1 Pro Preview', '2', '12', '0.20', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gemini-3.1-flash-lite-preview', 'Gemini 3.1 Flash Lite Preview', '0.25', '1.50', '0.025', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gemini-3-pro-preview', 'Gemini 3 Pro Preview', '2', '12', '0.2', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gemini-3-flash-preview', 'Gemini 3 Flash Preview', '0.5', '3', '0.05', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gemini-2.5-pro', 'Gemini 2.5 Pro', '1.25', '10', '0.125', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gemini-2.5-flash', 'Gemini 2.5 Flash', '0.3', '2.5', '0.03', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gemini-2.5-flash-lite', 'Gemini 2.5 Flash Lite', '0.10', '0.40', '0.01', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gemini-2.0-flash', 'Gemini 2.0 Flash', '0.10', '0.40', '0.025', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('step-3.5-flash', 'Step 3.5 Flash', '0.10', '0.30', '0.02', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('doubao-seed-code', 'Doubao Seed Code', '0.17', '1.11', '0.02', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('doubao-seed-2-0-pro', 'Doubao Seed 2.0 Pro', '0.47', '2.37', '0', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('doubao-seed-2-0-code', 'Doubao Seed 2.0 Code', '0.47', '2.37', '0', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('doubao-seed-2-0-lite', 'Doubao Seed 2.0 Lite', '0.25', '2', '0', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('doubao-seed-2-0-mini', 'Doubao Seed 2.0 Mini', '0.03', '0.31', '0', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('deepseek-v3.2', 'DeepSeek V3.2', '0.28', '0.42', '0.028', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('deepseek-v3.1', 'DeepSeek V3.1', '0.55', '1.67', '0.055', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('deepseek-v3', 'DeepSeek V3', '0.28', '1.11', '0.028', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('deepseek-chat', 'DeepSeek Chat', '0.27', '1.10', '0.07', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('deepseek-reasoner', 'DeepSeek Reasoner', '0.55', '2.19', '0.14', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('kimi-k2-thinking', 'Kimi K2 Thinking', '0.55', '2.20', '0.10', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('kimi-k2-0905', 'Kimi K2', '0.55', '2.20', '0.10', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('kimi-k2-turbo', 'Kimi K2 Turbo', '1.11', '8.06', '0.14', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('kimi-k2.5', 'Kimi K2.5', '0.60', '2.50', '0.10', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('kimi-k2.6', 'Kimi K2.6', '0.95', '4.00', '0.16', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('minimax-m2.1', 'MiniMax M2.1', '0.27', '0.95', '0.03', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('minimax-m2.1-lightning', 'MiniMax M2.1 Lightning', '0.27', '2.33', '0.03', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('minimax-m2', 'MiniMax M2', '0.27', '0.95', '0.03', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('minimax-m2.5', 'MiniMax M2.5', '0.12', '0.95', '0.03', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('minimax-m2.5-lightning', 'MiniMax M2.5 Lightning', '0.30', '2.40', '0.03', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('minimax-m2.7', 'MiniMax M2.7', '0.30', '1.20', '0.06', '0.375');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('minimax-m2.7-highspeed', 'MiniMax M2.7 Highspeed', '0.60', '2.40', '0.06', '0.375');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('glm-4.7', 'GLM-4.7', '0.39', '1.75', '0.04', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('glm-4.6', 'GLM-4.6', '0.28', '1.11', '0.03', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('glm-5', 'GLM-5', '1', '3.2', '0.2', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('glm-5.1', 'GLM-5.1', '1.4', '4.4', '0.26', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('mimo-v2-flash', 'Mimo V2 Flash', '0.09', '0.29', '0.009', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('mimo-v2-pro', 'MiMo V2 Pro', '1', '3', '0', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('qwen3.6-plus', 'Qwen3.6 Plus', '0.325', '1.95', '0', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('qwen3.5-plus', 'Qwen3.5 Plus', '0.26', '1.56', '0', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('qwen3-max', 'Qwen3 Max', '0.78', '3.90', '0', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('qwen3-235b-a22b', 'Qwen3 235B-A22B', '0.70', '8.40', '0', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('qwen3-coder-plus', 'Qwen3 Coder Plus', '0.65', '3.25', '0', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('qwen3-coder-flash', 'Qwen3 Coder Flash', '0.195', '0.975', '0', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('qwen3-coder-next', 'Qwen3 Coder Next', '0.12', '0.75', '0', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('qwq-plus', 'QwQ Plus', '0.80', '2.40', '0', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('qwq-32b', 'QwQ 32B', '0.20', '0.60', '0', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('qwen3-32b', 'Qwen3 32B', '0.16', '0.64', '0', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('grok-4.20-0309-reasoning', 'Grok 4.20 Reasoning', '2', '6', '0.20', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('grok-4.20-0309-non-reasoning', 'Grok 4.20', '2', '6', '0.20', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('grok-4-1-fast-reasoning', 'Grok 4.1 Fast Reasoning', '0.20', '0.50', '0.05', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('grok-4-1-fast-non-reasoning', 'Grok 4.1 Fast', '0.20', '0.50', '0.05', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('grok-4', 'Grok 4', '3', '15', '0.75', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('grok-code-fast-1', 'Grok Build 0.1 (Code Fast Alias)', '1', '2', '0.20', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('grok-3', 'Grok 3', '3', '15', '0.75', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('grok-3-mini', 'Grok 3 Mini', '0.25', '0.50', '0.075', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('codestral-2508', 'Codestral', '0.30', '0.90', '0.03', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('devstral-small-1.1', 'Devstral Small 1.1', '0.07', '0.28', '0.01', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('devstral-2-2512', 'Devstral 2', '0.40', '0.90', '0.04', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('devstral-medium', 'Devstral Medium', '0.40', '2', '0.04', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('mistral-large-3-2512', 'Mistral Large 3', '0.50', '1.50', '0.05', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('mistral-medium-3.1', 'Mistral Medium 3.1', '0.40', '2', '0.04', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('mistral-small-3.2-24b', 'Mistral Small 3.2', '0.075', '0.20', '0.01', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('magistral-medium', 'Magistral Medium', '2', '5', '0', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('command-a', 'Cohere Command A', '2.50', '10', '0', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('command-r-plus', 'Cohere Command R+', '2.50', '10', '0', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('command-r', 'Cohere Command R', '0.15', '0.60', '0', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('o3-pro', 'OpenAI o3-pro', '20', '80', '0', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('o3-mini', 'OpenAI o3-mini', '0.55', '2.20', '0.55', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('o1', 'OpenAI o1', '15', '60', '7.50', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('o1-mini', 'OpenAI o1-mini', '0.55', '2.20', '0.55', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('codex-mini', 'Codex Mini', '0.75', '3', '0.025', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5-mini', 'GPT-5 Mini', '0.25', '2', '0.025', '0');
INSERT INTO "model_pricing" ("model_id", "display_name", "input_cost_per_million", "output_cost_per_million", "cache_read_cost_per_million", "cache_creation_cost_per_million") VALUES ('gpt-5-nano', 'GPT-5 Nano', '0.05', '0.40', '0.005', '0');
INSERT INTO "prompts" ("id", "app_type", "name", "content", "description", "enabled", "created_at", "updated_at") VALUES ('v13-prompt', 'openclaw', 'V13 Prompt', 'fixture prompt', NULL, 1, NULL, NULL);
INSERT INTO "provider_endpoints" ("id", "provider_id", "app_type", "url", "added_at") VALUES (1, 'v13-claude', 'claude', 'https://v13.example', 13);
INSERT INTO "providers" ("id", "app_type", "name", "settings_config", "website_url", "category", "created_at", "sort_index", "notes", "icon", "icon_color", "meta", "is_current", "in_failover_queue", "cost_multiplier", "limit_daily_usd", "limit_monthly_usd", "provider_type") VALUES ('claude-official', 'claude', 'Claude Official', '{"env":{}}', 'https://www.anthropic.com/claude-code', 'official', 1785601459227, 0, NULL, 'anthropic', '#D4915D', '{}', 0, 0, '1.0', NULL, NULL, NULL);
INSERT INTO "providers" ("id", "app_type", "name", "settings_config", "website_url", "category", "created_at", "sort_index", "notes", "icon", "icon_color", "meta", "is_current", "in_failover_queue", "cost_multiplier", "limit_daily_usd", "limit_monthly_usd", "provider_type") VALUES ('codex-official', 'codex', 'OpenAI Official', '{"auth":{},"config":""}', 'https://chatgpt.com/codex', 'official', 1785601459227, 0, NULL, 'openai', '#00A67E', '{}', 0, 0, '1.0', NULL, NULL, NULL);
INSERT INTO "providers" ("id", "app_type", "name", "settings_config", "website_url", "category", "created_at", "sort_index", "notes", "icon", "icon_color", "meta", "is_current", "in_failover_queue", "cost_multiplier", "limit_daily_usd", "limit_monthly_usd", "provider_type") VALUES ('gemini-official', 'gemini', 'Google Official', '{"env":{},"config":{}}', 'https://ai.google.dev/', 'official', 1785601459227, 0, NULL, 'gemini', '#4285F4', '{}', 0, 0, '1.0', NULL, NULL, NULL);
INSERT INTO "providers" ("id", "app_type", "name", "settings_config", "website_url", "category", "created_at", "sort_index", "notes", "icon", "icon_color", "meta", "is_current", "in_failover_queue", "cost_multiplier", "limit_daily_usd", "limit_monthly_usd", "provider_type") VALUES ('v13-claude', 'claude', 'V13 Claude', '{"env":{"ANTHROPIC_BASE_URL":"https://v13.example"}}', NULL, NULL, NULL, 0, NULL, NULL, NULL, '{}', 1, 0, '1.0', NULL, NULL, NULL);
INSERT INTO "providers" ("id", "app_type", "name", "settings_config", "website_url", "category", "created_at", "sort_index", "notes", "icon", "icon_color", "meta", "is_current", "in_failover_queue", "cost_multiplier", "limit_daily_usd", "limit_monthly_usd", "provider_type") VALUES ('v13-hermes', 'hermes', 'V13 Hermes', '{"provider":"custom","api_key":"fixture"}', NULL, NULL, NULL, 0, NULL, NULL, NULL, '{}', 1, 0, '1.0', NULL, NULL, NULL);
INSERT INTO "providers" ("id", "app_type", "name", "settings_config", "website_url", "category", "created_at", "sort_index", "notes", "icon", "icon_color", "meta", "is_current", "in_failover_queue", "cost_multiplier", "limit_daily_usd", "limit_monthly_usd", "provider_type") VALUES ('v13-openclaw', 'openclaw', 'V13 OpenClaw', '{"baseUrl":"https://openclaw-v13.example"}', NULL, NULL, NULL, 0, NULL, NULL, NULL, '{}', 1, 0, '1.0', NULL, NULL, NULL);
INSERT INTO "proxy_config" ("app_type", "proxy_enabled", "listen_address", "listen_port", "enable_logging", "enabled", "auto_failover_enabled", "max_retries", "streaming_first_byte_timeout", "streaming_idle_timeout", "non_streaming_timeout", "circuit_failure_threshold", "circuit_success_threshold", "circuit_timeout_seconds", "circuit_error_rate_threshold", "circuit_min_requests", "default_cost_multiplier", "pricing_model_source", "created_at", "updated_at", "live_takeover_active") VALUES ('claude', 0, '127.0.0.1', 15721, 1, 0, 0, 6, 90, 180, 600, 8, 3, 90, 0.7, 15, '1', 'response', '2026-08-01 16:24:19', '2026-08-01 16:24:19', 0);
INSERT INTO "proxy_config" ("app_type", "proxy_enabled", "listen_address", "listen_port", "enable_logging", "enabled", "auto_failover_enabled", "max_retries", "streaming_first_byte_timeout", "streaming_idle_timeout", "non_streaming_timeout", "circuit_failure_threshold", "circuit_success_threshold", "circuit_timeout_seconds", "circuit_error_rate_threshold", "circuit_min_requests", "default_cost_multiplier", "pricing_model_source", "created_at", "updated_at", "live_takeover_active") VALUES ('codex', 0, '127.0.0.1', 15721, 1, 0, 0, 3, 60, 120, 600, 4, 2, 60, 0.6, 10, '1', 'response', '2026-08-01 16:24:19', '2026-08-01 16:24:19', 0);
INSERT INTO "proxy_config" ("app_type", "proxy_enabled", "listen_address", "listen_port", "enable_logging", "enabled", "auto_failover_enabled", "max_retries", "streaming_first_byte_timeout", "streaming_idle_timeout", "non_streaming_timeout", "circuit_failure_threshold", "circuit_success_threshold", "circuit_timeout_seconds", "circuit_error_rate_threshold", "circuit_min_requests", "default_cost_multiplier", "pricing_model_source", "created_at", "updated_at", "live_takeover_active") VALUES ('gemini', 0, '127.0.0.1', 15721, 1, 0, 0, 5, 60, 120, 600, 4, 2, 60, 0.6, 10, '1', 'response', '2026-08-01 16:24:19', '2026-08-01 16:24:19', 0);
INSERT INTO "settings" ("key", "value") VALUES ('common_config_upstream_semantics_migrated_v1', 'true');
INSERT INTO "settings" ("key", "value") VALUES ('official_providers_seeded', 'true');
INSERT INTO "skill_repos" ("owner", "name", "branch", "enabled") VALUES ('anthropics', 'skills', 'main', 1);
INSERT INTO "skill_repos" ("owner", "name", "branch", "enabled") VALUES ('ComposioHQ', 'awesome-claude-skills', 'master', 1);
INSERT INTO "skill_repos" ("owner", "name", "branch", "enabled") VALUES ('cexll', 'myclaude', 'master', 1);
INSERT INTO "skill_repos" ("owner", "name", "branch", "enabled") VALUES ('JimLiu', 'baoyu-skills', 'main', 1);
INSERT INTO "usage_daily_rollups" ("date", "app_type", "provider_id", "model", "request_model", "pricing_model", "request_count", "success_count", "input_tokens", "output_tokens", "cache_read_tokens", "cache_creation_tokens", "input_token_semantics", "total_cost_usd", "avg_latency_ms") VALUES ('2026-07-13', 'claude', 'v13-claude', 'fixture-model', '', '', 2, 2, 10, 5, 2, 1, 2, '0.33', 1.5);
INSERT INTO "usage_daily_rollups" ("date", "app_type", "provider_id", "model", "request_model", "pricing_model", "request_count", "success_count", "input_tokens", "output_tokens", "cache_read_tokens", "cache_creation_tokens", "input_token_semantics", "total_cost_usd", "avg_latency_ms") VALUES ('1970-01-01', 'claude', 'v13-claude', 'fixture-model', '', '', 1, 1, 10, 5, 2, 1, 2, '0.33', 15);
COMMIT;
PRAGMA foreign_keys=ON;
